---
services:
  iVentoy:
    image: garybowers/iventoy:latest
    container_name: iventoy
    restart: unless-stopped
    privileged: true
    hostname: iventoy
    volumes:
      - /data/iventoy/data:/iventoy/data
      - /data/iventoy/iso:/iventoy/iso
      - /data/iventoy/doc:/iventoy/doc 
      - /data/iventoy/lib:/iventoy/lib
      - /data/iventoy/log:/iventoy/log
      - /data/iventoy/usr:/iventoy/usr
    ports:
      - 26000:26000
      - 16000:16000
      - 10809:10809
      - 69:69/udp
    environment:
      - IVENTOY_AUTO_RUN=1
